spring:
  cloud:
    gateway:
      routes:
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: coupon_route
          uri: lb://mall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}
        - id: third_party_route
          uri: lb://mall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}
        - id: admin_route
          uri: lb://renren-fast
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}
        - id: mall_search_host
          uri: lb://mall-search
          predicates:
            - Host=search.olinmall.com
        - id: mall_auth_host
          uri: lb://mall-auth-server
          predicates:
            - Host=auth.olinmall.com
        - id: mall_cart_host
          uri: lb://mall-cart
          predicates:
            - Host=cart.olinmall.com
        - id: mall_seckill_host
          uri: lb://seckill-cart
          predicates:
            - Host=seckill.olinmall.com
        - id: mall_order_host
          uri: lb://mall-order
          predicates:
            - Host=order.olinmall.com
        - id: mall_member_host
          uri: lb://mall-member
          predicates:
            - Host=member.olinmall.com
        - id: mall_host
          uri: lb://mall-product
          predicates:
            - Host=olinmall.com,item.olinmall.com
